### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by changsijay** [elastic/homebrew-tap#24]
steps:

```
brew tap elastic/tap
brew install elastic/tap/elasticsearch-oss
brew services start elastic/tap/elasticsearch-oss
```

check the log at `/usr/local/var/log/elasticsearch.log`

```
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.002s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.002s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
    at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:118)
    at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:86)
    at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
    at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:92)
```

**Comment by changsijay** [comment]
fixed it by replace `logs/gc.log` by `/usr/local/var/log/gc.log` in `/usr/local/etc/elasticsearch/jvm.options`

**Comment by jasontedor** [comment]
This happens when you have a `jvm.options` from an older installation. When you upgrade or install again when such a `jvm.options` file already exists, Homebrew does not overwrite it. That means that this replacement: https://github.com/elastic/homebrew-tap/blame/597389e40e4c39839c9de4039521d590de80dc5f/Formula/elasticsearch-full.rb#L34 is not being made. For new installations, this is not a problem. The workaround, as you note, is to add this change to your existing `jvm.options` file.
