### ISSUE TITLE
Clean install of kibana-full 7.9.0 fails

### ISSUE THREAD

**Issue by cwhatley** [elastic/homebrew-tap#48]
Upgrade of kibana-full from 7.8.1 didn't succeed. Removed everything related to kibana in /usr/local and tried again from scratch with the same result. Here's the output from `kibana` on the command line:

```
Configuring logger failed: { Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at readFileSync (fs.js:369:19)
    at Keystore.load (/usr/local/Cellar/kibana-full/7.9.0/libexec/src/legacy/server/keystore/keystore.js:70:45)
    at new Keystore (/usr/local/Cellar/kibana-full/7.9.0/libexec/src/legacy/server/keystore/keystore.js:29:10)
    at readKeystore (/usr/local/Cellar/kibana-full/7.9.0/libexec/src/cli/serve/read_keystore.js:33:20)
    at applyConfigOverrides (/usr/local/Cellar/kibana-full/7.9.0/libexec/src/cli/serve/serve.js:164:41)
    at applyConfigOverrides (/usr/local/Cellar/kibana-full/7.9.0/libexec/src/cli/serve/serve.js:223:42)
    at MapSubscriber.RawConfigService.config$.rawConfigFromFile$.pipe.rawConfig [as project] (/usr/local/Cellar/kibana-full/7.9.0/libexec/src/core/server/config/raw_config_service.js:39:16)
    at MapSubscriber._next (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject._subscribe (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/ReplaySubject.js:76:28)
    at ReplaySubject.Observable._trySubscribe (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/Observable.js:44:25)
    at ReplaySubject.Subject._trySubscribe (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/Subject.js:102:51)
    at ReplaySubject.Observable.subscribe (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/Observable.js:30:22)
    at MapOperator.call (/usr/local/Cellar/kibana-full/7.9.0/libexec/node_modules/rxjs/internal/operators/map.js:32:23) errno: -21, syscall: 'read', code: 'EISDIR' }

 FATAL  Error: EISDIR: illegal operation on a directory, read
```

**Comment by DPattee** [comment]
Do you still encounter this? I’ve done many upgrades successfully over the past year
